Update Seafile license to reflect different licenses
awesome-selfhosted/awesome-selfhosted pull request #2237
Opened 2020-09-29 16:58 UTC by spbriggs

Different components are under different licenses https://download.seafile.com/published/seafile-manual/home.md

2020-09-29 18:41 UTC, SuperSandro2000 commented
I think your editor messes with a lot of the UTF-8 symbols in the file.

2020-09-29 18:42 UTC, SuperSandro2000 commented on README.md
> +- [Thingspeak](https://thingspeak.com/) - Open source "Internet of Things" application and API to store and retrieve data from things using HTTP. ([Demo](https://thingspeak.com/channels/public), [Sou
Every other character change except this one should be reverted.

2020-09-29 18:43 UTC, SuperSandro2000 requested changes

2020-09-29 18:43 UTC, SuperSandro2000 commented on README.md
> +- [Coquelicot](https://coquelicot.potager.org/) - Coquelicot is a "one-click" file sharing web application with a focus on protecting users' privacy. ([Source Code](https://coquelicot.potager.org/git
and this

2020-09-30 21:40 UTC, spbriggs commented
I'll have another try and submit a different PR. Apologies.

2020-09-30 21:40 UTC, closed without merging

2020-09-30 23:06 UTC, jnwatts commented
It's generally better to [amend](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) your commit and update the PR, rather than start a whole new one :-)