doc: add section for Usenet
awesome-selfhosted/awesome-selfhosted pull request #2277
Opened 2020-10-14 04:49 UTC by monperrus

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements (`Demo` and `Clients` are optional, don't add a duplicate `Source code` link if it is the same as the main link):

``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and marked `⊘ Proprietary`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks/specifc dialects.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is "Add aaa to bbb" for adding software aaa to section bbb. Do not call it "Update README.md".

2020-10-16 22:21 UTC, n8225 requested changes

2020-10-16 22:21 UTC, n8225 commented on README.md
> +### Usenet
Please add this to Misc/Other

"Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into Misc/Other."

2020-10-17 05:12 UTC, monperrus commented
ack, done.

2020-10-17 14:20 UTC, nodiscc requested changes

2020-10-17 14:20 UTC, nodiscc commented on README.md
> +- [InterNetNews](https://inn.eyrie.org/trac/) - Extremely flexible and configurable Usenet / netnews news server.
Missing license and Language/platform

2020-10-18 05:07 UTC, monperrus commented on README.md
> +- [InterNetNews](https://inn.eyrie.org/trac/) - Extremely flexible and configurable Usenet / netnews news server.
license not clear, closing. thanks.

2020-10-18 05:07 UTC, closed without merging