Add file share apps
awesome-selfhosted/awesome-selfhosted pull request #2337
Opened 2020-12-08 20:08 UTC by mzch

Add file share apps to `Single-click/drag-n-drop upload`

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements (`Demo` and `Clients` are optional, don't add a duplicate `Source code` link if it is the same as the main link):

``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and marked `⊘ Proprietary`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks/specifc dialects.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is "Add aaa to bbb" for adding software aaa to section bbb. Do not call it "Update README.md".

2020-12-10 19:24 UTC, youhost-joseph commented
I've tested an install of shafi (https://github.com/dealfonso/shafi) on Apache and PHP 7.2.
No way to make this work: install.php makes a blank page and manual config works but upload gives error.
I'm afraid this software is unmaintained.
May be the docker works...

2020-12-12 14:35 UTC, nodiscc requested changes

2020-12-12 14:35 UTC, nodiscc commented on README.md
> +- [FireShare](https://auspham.dev/FireShare/) - 🔥A Full-Stack, Pub-Sub, Real-time secure file sharing system. Using NodeJS, ReactJS, SocketIO, MongoDB. Chai, WebdriverIO for testing. `Nodejs` `MIT`
No source code link, please remove this

2020-12-12 14:35 UTC, nodiscc commented on README.md
> +- [BlackUpload](https://github.com/FarisCode511/BlackUpload) - An Anonymus File Uploader Script with Multi-File Upload Support. `MIT` `PHP`
There is no license in the repository, please remove this until a proprer license is added

2020-12-12 14:35 UTC, nodiscc commented on README.md
> +- [Kleeja](https://kleeja.net/) - ⬇️ File Upload/sharing application, used by thousands of webmasters since 2007. ([Source Code](https://github.com/kleeja-official/kleeja)) `GPL-2.0` `PHP`
please remove the funky ⬇️ symbol, text descriptions only please

2020-12-12 14:35 UTC, nodiscc commented on README.md
> +- [gdprshare](https://github.com/lixmal/gdprshare) - web application to share files with GDPR compliance in mind. `MIT` `Go`
reviewed ok

2020-12-12 14:36 UTC, nodiscc commented
I reviewed some of the items, please make the required changes. More generally I would advise only adding one or 2 items max. per Pull Request. Reviewing this will take longer

2020-12-12 14:48 UTC, mzch commented
OK. I'll make another PR. I've just closed this PR.

2020-12-12 14:48 UTC, closed without merging

2020-12-12 14:55 UTC, mzch commented
> I've tested an install of shafi (https://github.com/dealfonso/shafi) on Apache and PHP 7.2.
> No way to make this work: install.php makes a blank page and manual config works but upload gives error.
> I'm afraid this software is unmaintained.
> May be the docker works...

On my instance, ShaFi works completely. Debian 10.7 + Apache 2.4 + PHP 7.3. Perhaps something lacks in your environment.

2020-12-20 17:53 UTC, youhost-joseph commented
> On my instance, ShaFi works completely. Debian 10.7 + Apache 2.4 + PHP 7.3. Perhaps your environment lacks something.

Good, I sure lack something in my environment as I tried again but no way. Thank you for pointing this out so people knows it works.