Update Send entry
awesome-selfhosted/awesome-selfhosted pull request #2377
Opened 2021-01-14 16:39 UTC by timvisee

There are multiple clients at different locations. Added them separately here. Is this the correct way to proceed?

---

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of
  - [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management),
  - [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics),
  - [staticgen.com](https://www.staticgen.com/)
  - [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2021-01-23 09:06 UTC, nodiscc requested changes
> Is this the correct way to proceed?

Nope, we only support a single `Clients` link. The correct way would be adding/maintaining a "Clients" documentation page/README section at https://gitlab.com/timvisee/send, and link to there instead

2021-01-24 20:41 UTC, timvisee commented
> > Is this the correct way to proceed?
> 
> Nope, we only support a single `Clients` link. The correct way would be adding/maintaining a "Clients" documentation page/README section at https://gitlab.com/timvisee/send, and link to there instead

@nodiscc Thanks. Made the change.

2021-01-31 15:52 UTC, nodiscc approved these changes

2021-02-06 13:18 UTC, nodiscc requested changes

2021-02-06 13:18 UTC, nodiscc commented on README.md
> +- [Send](https://github.com/timvisee/send) - Simple, private, end to end encrypted temporary file sharing, originally built by Mozilla. ([Source Code](https://github.com/timvisee/send), [Clients](htt
Sorry, the duplicate  `Source code` link needs to be removed

2021-02-13 13:51 UTC, nodiscc approved these changes

2021-02-13 13:51 UTC, merged

2021-02-13 14:52 UTC, timvisee commented
Sorry for the trouble. Thanks for looking into it!