Adds calendso to Booking and Scheduling
awesome-selfhosted/awesome-selfhosted pull request #2502
Opened 2021-04-16 06:52 UTC by asm0dey

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [ x Additions are not already listed at any of
  - [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management),
  - [awesome-analytics](https://github.com/onurakpolat/awesome-analytics) (analytics),
  - [staticgen.com](https://www.staticgen.com/)
  - [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] The `Language` tag is the main server-side requirement for the software - don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2021-04-16 20:01 UTC, nodiscc requested changes

2021-04-16 20:01 UTC, nodiscc commented on README.md
> +- [calendso](https://calendso.com/), [Source Code](https://github.com/calendso/calendso) -  The open-source Calendly alternative.  ([Demo](https://app.calendso.com/bailey)) `MIT` `Nodejs`
Please fix formatting

```
- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` 
```

2021-04-16 20:37 UTC, asm0dey commented on README.md
> +- [calendso](https://calendso.com/), [Source Code](https://github.com/calendso/calendso) -  The open-source Calendly alternative.  ([Demo](https://app.calendso.com/bailey)) `MIT` `Nodejs`
Fixed, sorry for inconvinience

2021-04-17 08:14 UTC, asm0dey commented
Excuse me, I don't understand why does it fail :(

2021-04-17 20:48 UTC, marcelbrueckner commented
> Excuse me, I don't understand why does it fail :(

Your addition contains duplicate spaces. I've inserted `_` below at the positions where you placed them, two in total. If you remove them, the pipeline will probably run through.

```markdown
- [calendso](https://calendso.com/) - _The open-source Calendly alternative. _([Demo](https://app.calendso.com/bailey), [Source Code](https://github.com/calendso/calendso)) `MIT` `Nodejs`
```

2021-04-17 21:23 UTC, asm0dey commented
Thank you for pointing this to me!

2021-05-13 18:50 UTC, prayashm commented on README.md
> +- [calendso](https://calendso.com/) - The open-source Calendly alternative. ([Demo](https://app.calendso.com/bailey), [Source Code](https://github.com/calendso/calendso)) `MIT` `Nodejs`
Let's order them:
```suggestion
- [Calendso](https://calendso.com/) - The open-source Calendly alternative. ([Demo](https://app.calendso.com/bailey), [Source Code](https://github.com/calendso/calendso)) `MIT` `Nodejs`
- [Easy!Appointments](http://easyappointments.org/) - A highly customizable web application that allows your customers to book appointments with you via the web. ([Demo](http://easyappointments.org/demo/), [Source Code](https://github.com/alextselegidis/easyappointments)) `GPL-3.0` `PHP`
```

2021-05-30 12:45 UTC, nodiscc requested changes
> The open-source Calendly alternative

I have no idea about what calendly is/does and therefore no idea of what calendso is/does. Please clarify the description

2021-05-30 12:57 UTC, asm0dey commented
@nodiscc done

2021-06-06 12:08 UTC, nodiscc approved these changes

2021-06-23 20:12 UTC, merged