Add Track Awesome List
awesome-selfhosted/awesome-selfhosted pull request #2604
Opened 2021-07-02 19:40 UTC by theowenyoung

Hi,

Like I mentioned at https://github.com/awesome-selfhosted/awesome-selfhosted/issues/89#issuecomment-872123870 , I added a Track Awesome List Badge at the documataion.

I'm a big fan of awesome-selfhosted. After discovering this awesome list, I read all kinds of interesting items in the entire list. After that, I wanted to see what updates were made to this list every once in a while, and had to go through Github's commit history to see what was updated for each commit. To be honest, it was quite a poor reading experience.

So for this need, I created [Track Awesome List](https://www.trackawesomelist.com) in my spare time, and created a profile for awesome-selfhosted, https://www.trackawesomelist.com/awesome-selfhosted/awesome-selfhosted . With this link, we can read the latest updates of awesome-selfhosted by day/week, free, daily updated. I wonder if anyone else has this need to see the latest updates, and if so, whether to add this badge in the readme to tell others they can see the updates via this link?

Let me know what you think. I'm happy to receive any feedback or suggestions for improvement. I want this to be as useful as possible.

If you don’t think it’s necessary, that’s okay. I really appreciate you maintaining such an awesome list. I like this list.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2021-07-06 16:12 UTC, arylatt approved these changes

2021-07-07 16:18 UTC, nodiscc requested changes
I don't think we should (hot)link a badge from a third-party site, which can change without notice, etc. Can you please add it in https://github.com/awesome-selfhosted/awesome-selfhosted#external-links instead? With a concise description. This is where we store related projects (the `awesome` badge is ... different because the maintainer required us to add the badge to be added to the main `awesome` list)

Thanks

Also related https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2235

2021-07-07 16:46 UTC, theowenyoung commented
That's okay! I'll make a change with that.

I didn't notice #2235 before, but the issue is exactly my issue before, that's why I created trackawesomelist.com.

I created a workflow automatically to parse awesome-selfhosted's readme, and getting every items' commit time, then generate a static html page for it.

2021-07-08 16:00 UTC, n8225 approved these changes

2021-07-12 17:50 UTC, nodiscc approved these changes

2021-07-12 17:51 UTC, merged