Added Remotely to Gateways and Terminal Sharing
awesome-selfhosted/awesome-selfhosted pull request #2741
Opened 2021-11-01 13:51 UTC by bykof

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2021-12-04 19:27 UTC, Vendetta26 commented
awesome-selfhosted:master
bykof:patch-1

2021-12-04 19:27 UTC, Vendetta26 requested changes
awesome-selfhosted:master
bykof:patch-1

2021-12-19 09:12 UTC, bykof reviewed
LGTM

2021-12-25 20:39 UTC, nodiscc requested changes
please add the entry in alphabetical order

2021-12-26 16:50 UTC, nodiscc requested changes

2021-12-26 16:50 UTC, nodiscc commented on README.md
> +computing. ([Source Code](https://github.com/shellhub-io/shellhub)) `Apache-2.0` `Go/Other`
please remove the accidental line break in the ShellHub entry

2021-12-26 16:50 UTC, nodiscc commented on README.md
> +- [remotely](https://remotely.one/) - A remote control and remote scripting solution, built with .NET 5, Blazor, SignalR Core, and WebRTC. Teamviewer alternative ([Source Code](https://github.com/imm
Missing `.` at the end of the description

2021-12-26 16:50 UTC, nodiscc commented on README.md
> +- [remotely](https://remotely.one/) - A remote control and remote scripting solution, built with .NET 5, Blazor, SignalR Core, and WebRTC. Teamviewer alternative ([Source Code](https://github.com/imm
The correct license is `GPL-3.0`

2022-01-18 17:03 UTC, nodiscc commented
@bykof ping

2022-02-22 19:52 UTC, closed without merging