Added a new category of low code tools
awesome-selfhosted/awesome-selfhosted pull request #2781
Opened 2021-12-10 06:23 UTC by Nikhil-Nandagopal

Added a new category for low code tools and updated information on Appsmith

2021-12-12 15:31 UTC, Epy commented
Hello
The demo link for ERPNext is the demo from Appsmith

Also why did you put duplicate Appsmith links ?

2021-12-13 10:29 UTC, Nikhil-Nandagopal commented
@Epy thanks for catching that! I've now fixed the link.

I've listed Appsmith under different categories because the category used to be called ERP but it's now also called low code and Appsmith is an IDE

2022-03-27 15:01 UTC, nodiscc requested changes
Sorry for the delay

- Please remove duplicate `ApppSmith` entries since it's already being added to `Low code`
- Should be `Low-code`
- There are several "Low-code" solutions already listed, please move them to the new section

2022-03-28 12:30 UTC, Nikhil-Nandagopal commented
@nodiscc I've made the changes

2022-03-28 20:15 UTC, nodiscc requested changes

2022-03-28 20:15 UTC, nodiscc commented on README.md
> +- [ERPNext](https://erpnext.com) - Free and Open Source Enterprise Resource Planning (ERP). ([Demo](https://erpnext.com), [Source Code](https://github.com/frappe/erpnext)) `GPL-3.0` `Python`
ERPNext should be in the REP category, not in the Low-Code category

2022-04-11 09:20 UTC, nodiscc commented on README.md
> +- [ERPNext](https://erpnext.com) - Free and Open Source Enterprise Resource Planning (ERP). ([Demo](https://erpnext.com), [Source Code](https://github.com/frappe/erpnext)) `GPL-3.0` `Python`
ping @Nikhil-Nandagopal

2022-05-14 22:04 UTC, nodiscc commented
1 month without reply, closing.

2022-05-14 22:04 UTC, closed without merging