Add CasaOS
awesome-selfhosted/awesome-selfhosted pull request #2840
Opened 2022-01-21 17:38 UTC by MohamedElashri

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-08-10 17:24 UTC, KieranRobson approved these changes

2022-08-31 16:19 UTC, tigerinus commented
Hello - I am a contributor to CasaOS. 

I see `feedback needed` tag. What is it needed to move this forward?

Appreciated!

2022-08-31 20:34 UTC, nodiscc requested changes

2022-08-31 21:53 UTC, tigerinus commented on README.md
> +- [CasaOS](https://www.casaos.io/) - A simple, easy-to-use, elegant open-source Home Cloud system. ([Source Code](https://github.com/IceWhaleTech/CasaOS)) ` Apache-2.0` `Go`
@nodiscc - It is correct that `get.sh` installs static binary built from Go and Docker as a dependency.

@MohamedElashri - Would you be able to help make these changes?

Thanks all!

2022-09-03 03:23 UTC, MohamedElashri commented on README.md
> +- [CasaOS](https://www.casaos.io/) - A simple, easy-to-use, elegant open-source Home Cloud system. ([Source Code](https://github.com/IceWhaleTech/CasaOS)) ` Apache-2.0` `Go`
@nodiscc @tigerinus 

I added the required changes, I hope that it is good to be merged now.

2022-09-03 16:30 UTC, tigerinus commented on README.md
> +- [CasaOS](https://www.casaos.io/) - A simple, easy-to-use, elegant open-source Home Cloud system. ([Source Code](https://github.com/IceWhaleTech/CasaOS)) ` Apache-2.0` `Go`
@nodiscc - can u help to click the merge button?

2022-09-05 22:40 UTC, tigerinus approved these changes

2022-09-07 08:31 UTC, nodiscc approved these changes

2022-09-07 19:04 UTC, tigerinus commented
@MohamedElashri would you be able to merge? Thx.

2022-09-14 14:16 UTC, MohamedElashri commented
> 

I don't have the permissions to merge. I'm not a project maintainer

2022-09-14 14:17 UTC, MohamedElashri commented
> @MohamedElashri would you be able to merge? Thx.

@tigerinus  I don't have the permissions to merge. I'm not a project maintainer

2022-09-14 21:41 UTC, merged