Added SimpleX to Custom Communication Systems
awesome-selfhosted/awesome-selfhosted pull request #2851
Opened 2022-01-26 00:39 UTC by vsevolod-mineev

This fantastic self-hosted secure messenger competitor has recently released v1.0 and has it's eyes set on Signal, Telegram and WeChat.

The project is free, decentralised, open source, self-hosted and has been featured on awesome-haskell and awesome-privacy.

2022-02-01 15:27 UTC, belencordoba007 approved these changes
DONE

2022-02-01 16:44 UTC, vsevolod-mineev commented
> please re-add the [pull request template](https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/.github/PULL_REQUEST_TEMPLATE.md) to the description of your pull request, and check relevant boxes

Done.

2022-02-01 17:13 UTC, nodiscc requested changes

2022-02-01 17:34 UTC, vsevolod-mineev commented on README.md
> +- [SimpleX Chat](https://github.com/simplex-chat/simplex-chat) - The most private and secure chat and applications platform - now with double ratchet E2E encryption!
Added license and language.

2022-02-01 17:35 UTC, vsevolod-mineev commented on README.md
> +- [SimpleX Chat](https://github.com/simplex-chat/simplex-chat) - The most private and secure chat and applications platform - now with double ratchet E2E encryption!
> missing license and language/platform

Added license and language.

2022-02-01 18:23 UTC, vsevolod-mineev commented
Done.

2022-02-02 00:54 UTC, vsevolod-mineev commented
Changed "!" to "." since this fits better with the overall consensus for this document.

2022-02-07 09:23 UTC, vsevolod-mineev commented
Is there anything else preventing this from being merged?

Still eagerly waiting for us to be features.

Kindest regards,
VM

2022-02-22 19:51 UTC, nodiscc approved these changes

2022-02-22 19:51 UTC, merged