Include OpenZiti as a zero trust overlay network
awesome-selfhosted/awesome-selfhosted pull request #2997
Opened 2022-05-07 02:10 UTC by dovholuknf

Protect your services using a zero trust overlay network. Excellent for self-hosted virtual private servers (VPS). Generic enough to support any service/project you want to expose to friends, family, colleagues, etc

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-05-07 09:15 UTC, fbartels requested changes
>  Any category you are creating has the minimum requirement of 3 items.
If not, your addition may be inserted into Misc/Other.

This requirement is not fulfilled by this PR.

2022-05-07 14:51 UTC, dovholuknf commented
Oh my misunderstanding. That makes perfect sense now, for some reason I thought that referred to the github labels. But this makes way more sense. Is it acceptable to move other rows from misc. to here or is it more appropriate to just list two others?

I moved it under misc. for now thank you!

2022-05-09 16:59 UTC, dovholuknf commented
🤦 fixing

2022-05-09 17:01 UTC, dovholuknf commented
thank you. fixed.

2022-05-10 11:10 UTC, fbartels approved these changes

2022-05-23 18:32 UTC, dovholuknf commented on README.md
> +- [OpenZiti](https://openziti.github.io/) - Fully-featured, self-hostable, zero trust overlay network. Includes a full mesh overlay network, includes 2FA support out of the box, includes clients for
Go is what the 'server side' is written in so I can update that. The other's are the "client side" languages available. I'll update to `go`. Thanks

2022-06-02 11:31 UTC, dovholuknf commented
@nodiscc - changed implemented. thank you!

2022-06-20 13:56 UTC, dovholuknf commented
Howdy @nodiscc , I made the requested change. Hopefully, I've gotten it all sorted now

2022-06-20 20:46 UTC, nodiscc approved these changes

2022-06-27 11:33 UTC, dovholuknf commented
Thank you, @nodiscc, for approving. What's the process for merging this back now? I expect that it's just whenever someone come around to check for mergable prs?

2022-07-03 15:26 UTC, merged