added  Discord bots  to README.md
awesome-selfhosted/awesome-selfhosted pull request #3023
Opened 2022-05-22 10:36 UTC by alainseys

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-05-22 13:02 UTC, kokomo123 requested changes
Typoed a bit there, DiscordBotPanel, Discord Bot Panel Platform, then the .

2022-05-25 19:31 UTC, KieranRobson requested changes
Two links leading to the same place is probably unnecessary. The first link should link to the site to download the tool. 

If there is no link, then the first hyperlink  `[DisocrdBotPanel(https://github.com/jareer12/DiscordBotPanel)` could be the source code, and then no source code link would be needed.

2022-05-25 20:20 UTC, nodiscc requested changes

2022-05-25 20:21 UTC, nodiscc commented on README.md
> +- [DisocrdBotPanel](https://github.com/jareer12/DiscordBotPanel) - DiscordBotPanelplatform to manage your Discord bots . ([Source Code](https://github.com/jareer12/DiscordBotPanel
- please remove the extra space before `.`

2022-05-28 09:31 UTC, jareer12 commented
Thanks to everyone for helping.

2022-06-05 15:27 UTC, nodiscc commented on README.md
> +- [DisocrdBotPanel](https://github.com/jareer12/DiscordBotPanel) - DiscordBotPanelplatform to manage your Discord bots . ([Source Code](https://github.com/jareer12/DiscordBotPanel
@alainseys ping

2022-07-15 11:06 UTC, nodiscc commented
No reply for a month, closing.

2022-07-15 11:06 UTC, closed without merging