Added Yarr to Feed Readers
awesome-selfhosted/awesome-selfhosted pull request #3122
Opened 2022-07-16 13:53 UTC by KieranRobson

Closes #2996 
Source code for clickables: https://github.com/nkanaev/yarr
Installation: https://github.com/nkanaev/yarr#usage

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software)
  must be added to `non-free.md` and marked `⊘ Proprietary`:
  ``- [Name](http://homepage/) `⊘ Proprietary` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-07-25 15:15 UTC, nodiscc requested changes

2022-07-25 15:15 UTC, nodiscc commented on README.md
> +- [Yarr](https://github.com/nkanaev/yarr) - Yarr (yet another rss reader) is a web-based feed aggregator which can be used both as a desktop application and a personal self-hosted server. `MIT` `Go`a
typo at the end of the line extra (`a` after the language tag)

2022-07-25 17:18 UTC, KieranRobson commented
Merge conflicts and Typo fixed

2022-07-31 22:07 UTC, nodiscc commented
There is something wrong with this patch: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3122/files it re-add `Winds` which was removed in https://github.com/awesome-selfhosted/awesome-selfhosted/commit/1a26cae08b5ff867a4f30f803b1b92398c99438a

The easiest way to fix this is to rebase on top of master and squash all commits together

2022-07-31 22:07 UTC, nodiscc requested changes
There is something wrong with this patch: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3122/files it re-adds `Winds` which was removed in https://github.com/awesome-selfhosted/awesome-selfhosted/commit/1a26cae08b5ff867a4f30f803b1b92398c99438a

The easiest way to fix this is to rebase on top of master and squash all commits together

2022-07-31 22:20 UTC, KieranRobson commented
This should be good now I believe

2022-08-01 06:12 UTC, nodiscc approved these changes

2022-08-08 12:37 UTC, merged