Adding 'Resoto' to the Software Development - IDE & Tools category.md
awesome-selfhosted/awesome-selfhosted pull request #3251
Opened 2022-08-23 07:24 UTC by scapecast

Proposing to add Resoto, our open source cloud asset inventory, to the development / IDE category.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-08-23 08:29 UTC, KieranRobson requested changes
Thanks for the contrbution!

A couple changes to be made

2022-08-23 08:29 UTC, KieranRobson commented on README.md
> +- [Resoto] (https://resoto.com) - Resoto is an open source cloud asset inventory. Write code that reacts to changes in your cloud infrastructure. Resoto helps you search infrastructure, generate repo
- Please remove the extra space between [Resoto] and (https://resoto.com)

> https://resoto.com/docs#what-is-resoto

-  Please change the description to  `Create indexes resources, captures dependencies, and maps out your infrastructure in an intuitive [graph](https://resoto.com/docs/concepts/graph). The graph contains metrics for each [resource](https://resoto.com/docs/reference/data-models).`

2022-08-25 11:12 UTC, KieranRobson approved these changes
LGTM

2022-09-02 22:52 UTC, nodiscc requested changes

2022-09-02 22:52 UTC, nodiscc commented on README.md
> +- [Resoto](https://resoto.com) - Resoto creates an inventory of your cloud, indexes resources, captures dependencies, and maps out your infrastructure in an intuitive [graph](https://resoto.com/docs/
- Missing `.` at the end of the description
- Please remove inline links to graph/resource.

2022-10-09 18:03 UTC, nodiscc commented
No reply for > a month, closing.

2022-10-09 18:03 UTC, closed without merging