Add MiroTalk to Communication
awesome-selfhosted/awesome-selfhosted pull request #3254
Opened 2022-08-25 09:54 UTC by miroslavpejic85

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-08-25 10:16 UTC, KieranRobson commented on README.md
> +- [MiroTalk SFU](https://sfu.mirotalk.com) - WebRTC SFU - simple, secure, scalable real-time video conferences compatible with all browsers and platforms. ([Demo](https://sfu.mirotalk.com/newroom), [
The description should say what the software does. 
- Please change the description to `Simple, secure, scalable real-time video conferences up to 4k, compatible with all browsers and platforms.`

> https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md
- Please change the language tag to `Docker/Nodejs`

2022-08-25 10:20 UTC, KieranRobson commented on README.md
> +- [MiroTalk P2P](https://p2p.mirotalk.com) - WebRTC P2P - simple, secure, fast real-time video conferences compatible with all browsers and platforms. ([Demo](https://p2p.mirotalk.com/newcall), [Sour
The description should say what the software does. 
- Please change the description to `Simple, secure, scalable real-time video conferences up to 4k, compatible with all browsers and platforms.`

> https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md
- Please change the language tag to `Nodejs/Docker`

2022-08-25 10:21 UTC, KieranRobson requested changes
What is the difference between the two software added? Both have the same description, are both needed to run microtalk?

2022-08-25 10:26 UTC, miroslavpejic85 commented
> What is the difference between the two software added? Both have the same description, are both needed to run microtalk?

Hello Kieran, 
The difference between the 2 projects you can check [here](https://github.com/miroslavpejic85/mirotalksfu/issues/14#issuecomment-932701999)
Thank you!

2022-08-25 11:02 UTC, KieranRobson requested changes
Couple more changed to be made

2022-08-25 11:02 UTC, KieranRobson commented on README.md
> +- [MiroTalk P2P](https://p2p.mirotalk.com) - WebRTC P2P - Simple, secure, fast real-time video conferences up to 4k and 60fps, compatible with all browsers and platforms. ([Demo](https://p2p.mirotalk
As P2P is mentioned in the name of the application, please remove ` WebRTC P2P -`. This will make it fit the standard of the list.

2022-08-25 11:02 UTC, KieranRobson commented on README.md
> +- [MiroTalk SFU](https://sfu.mirotalk.com) - WebRTC SFU - Simple, secure, scalable real-time video conferences up to 4k, compatible with all browsers and platforms. ([Demo](https://sfu.mirotalk.com/n
As SFU is mentioned in the name of the application, please remove `WebRTC SFU-`. This will make it fit the standard of the list.

2022-08-25 11:07 UTC, KieranRobson approved these changes
Although these should be within two different PRs due to not being dependant on each other, Ill approve this as they are the same name brand. 

LGTM

2022-08-25 11:08 UTC, miroslavpejic85 commented
> Although these should be within two different PRs due to not being dependant on each other, Ill approve this as they are the same name brand.
> 
> LGTM

Yeah, Thank you so much!

2022-08-25 13:39 UTC, miroslavpejic85 commented
But the PR is still open? did I miss something?

2022-08-25 14:07 UTC, KieranRobson commented
> But the PR is still open? did I miss something?

I dont have merging rights sadly but I can help clear up any errors with submissions so that theyre more likely to be merged when nodiscc is available haha

2022-09-02 22:50 UTC, nodiscc approved these changes
Thanks!

2022-09-03 07:10 UTC, miroslavpejic85 commented
Hello nodiscc,

Thanks to you! it would be great if you add MiroTalk to Communication.  Tell me if something is missing, I see the addition label, but the PR is still open :) Thanks again and have a good weekend!

2022-09-12 23:03 UTC, nodiscc approved these changes

2022-09-12 23:03 UTC, merged