addition: Add Gerrit to Project Management
awesome-selfhosted/awesome-selfhosted pull request #3298
Opened 2022-09-19 16:35 UTC by KieranRobson

Closes #3295 
Source Code: https://github.com/GerritCodeReview/gerrit

Installation:
https://github.com/GerritCodeReview/gerrit#use-pre-built-gerrit-images-on-docker

> Use pre-built Gerrit images on Docker
> Docker images of Gerrit are available on [DockerHub](https://hub.docker.com/u/gerritforge/)
> To run a CentOS 8 based Gerrit image:
>    `docker run -p 8080:8080 gerritcodereview/gerrit[:version]-centos8`
> To run a Ubuntu 20.04 based Gerrit image:
>    `docker run -p 8080:8080 gerritcodereview/gerrit[:version]-ubuntu20`
> NOTE: release is optional. Last released package of the version is installed if the release number is omitted.

https://gerrit-documentation.storage.googleapis.com/Documentation/3.6.1/linux-quickstart.html#_before_you_start

> Be sure you have:
>
> A Unix-based server, including any Linux flavor, MacOS, or Berkeley Software Distribution (BSD).
>
> Java SE Runtime Environment version 11 and up.

-----

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-09-20 22:20 UTC, nodiscc requested changes

2022-09-20 22:20 UTC, nodiscc commented on README.md
> +- [Gerrit](https://www.gerritcodereview.com/) - A code review and project management tool for Git based projects. ([Source Code](https://github.com/GerritCodeReview/gerrit)) `Apache-2.0` `Docker/Java
>https://gerrit-documentation.storage.googleapis.com/Documentation/3.6.1/linux-quickstart.html

The recommended way to run the program is by running `java -jar`, please change the language/platform to `Java/docker` to reflect this.

2022-09-21 11:09 UTC, nodiscc approved these changes

2022-09-21 18:55 UTC, pandrey2003 approved these changes

2022-10-02 15:02 UTC, merged