add tubesync to automation
awesome-selfhosted/awesome-selfhosted pull request #3300
Opened 2022-09-19 17:50 UTC by CrimsonTome

Closes #3297

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-09-19 18:11 UTC, KieranRobson commented on README.md
> +- [tubesync](https://github.com/meeb/tubesync) - Syncs YouTube channels and playlists to a locally hosted media server. `AGPL-3.0` `Docker`
> https://github.com/meeb/tubesync#manual-non-containerised-installation
- Please change the language to `Docker/Python`

2022-09-19 18:12 UTC, KieranRobson requested changes
Couple of changes to be made!

2022-09-19 18:12 UTC, KieranRobson commented on README.md
> +- [tubesync](https://github.com/meeb/tubesync) - Syncs YouTube channels and playlists to a locally hosted media server. `AGPL-3.0` `Docker`
As this software utilises YouTube which is out of the users control, please add `⚠` to the start of the entry

2022-09-19 18:12 UTC, KieranRobson commented on README.md
> +- [tubesync](https://github.com/meeb/tubesync) - Syncs YouTube channels and playlists to a locally hosted media server. `AGPL-3.0` `Docker`
> https://github.com/meeb/tubesync#manual-non-containerised-installation
- Please change the language tag to `Docker/Python`

2022-09-19 21:28 UTC, KieranRobson approved these changes
Looks good to me!

2022-09-21 10:53 UTC, nodiscc approved these changes

2022-09-28 16:58 UTC, merged