add lemon chat
awesome-selfhosted/awesome-selfhosted pull request #3419
Opened 2022-11-21 14:31 UTC by azc5OQ

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-11-23 12:41 UTC, kokomo123 requested changes
More useful description is needed, along with capitalizing the first letter of h, j, and r in the language. Then it should be all set to merge.

2022-11-23 22:00 UTC, azc5OQ commented
done

2022-11-25 01:14 UTC, kokomo123 approved these changes
Thanks! Now i'm deeming this all set to merge 👍🏻

2023-01-14 10:15 UTC, azc5OQ commented
so, is this going to be merged or what is the next step
is the chat not good enough?

2023-02-28 21:12 UTC, azc5OQ commented
so, how about it then?

2023-03-07 16:25 UTC, nodiscc requested changes

2023-03-07 16:25 UTC, nodiscc commented on README.md
> +- [LemonChat](https://github.com/azc5OQ/lemon-chat) - Communication system with focus on simplicity and security `GPL-3.0` `Html/Javascript/Rust`
```suggestion
- [LemonChat](https://github.com/azc5OQ/lemon-chat) - Communication system with focus on simplicity and security. `GPL-3.0` `Rust`
```

2023-03-07 17:40 UTC, azc5OQ commented on README.md
> +- [LemonChat](https://github.com/azc5OQ/lemon-chat) - Communication system with focus on simplicity and security `GPL-3.0` `Html/Javascript/Rust`
ok

2023-03-07 17:42 UTC, azc5OQ commented on README.md
> +- [LemonChat](https://github.com/azc5OQ/lemon-chat) - Communication system with focus on simplicity and security `GPL-3.0` `Html/Javascript/Rust`
Im ok with these changes

2023-03-08 18:24 UTC, azc5OQ commented
lol

2023-03-12 18:37 UTC, azc5OQ commented
I do not know how I can make the simple change that you are asking for. Maybe if I opened new pull request (but I do not know if that is allowed)

Maybe you could just add this small change yourselves? Or is there some other problem?

2023-03-12 18:38 UTC, azc5OQ commented
Is this chat not worthy of being "awesome selfhosted?"

2023-03-13 21:11 UTC, closed without merging