Add Sonic as search engines
awesome-selfhosted/awesome-selfhosted pull request #3481
Opened 2022-12-29 10:36 UTC by rickytato

Fast, lightweight & schema-less search backend. An alternative to Elasticsearch that runs on a few MBs of RAM.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding has working installation instructions.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2022-12-29 10:39 UTC, KieranRobson requested changes
Couple changes to be made

2022-12-29 10:39 UTC, KieranRobson commented on README.md
> +- [sonic](https://github.com/valeriansaliou/sonic) - Sonic is a fast, lightweight and schema-less search backend. It ingests search texts and identifier tuples that can then be queried against in a m
Please change `rust` to `Rust`

2022-12-29 10:39 UTC, KieranRobson commented on README.md
> +- [sonic](https://github.com/valeriansaliou/sonic) - Sonic is a fast, lightweight and schema-less search backend. It ingests search texts and identifier tuples that can then be queried against in a m
Please change `MPL-2.0 license` to `MPL-2.0`

2023-01-01 16:02 UTC, kokomo123 approved these changes
Looks good to merge after changes were made.

2023-01-04 23:20 UTC, nodiscc reviewed
As far as I can see, there is no way to query this search engine over the network, without implementing one of the client libraries in your program?

We only list end-user applications, not development toolkits or libraries, so adding this might not be relevant.

2023-01-14 11:56 UTC, nodiscc requested changes
@rickytato please check the relevant boxes in the PR description. Also please address the question above.

2023-01-15 21:20 UTC, kokomo123 reviewed
Nevermind then on my review. I think this isn't fit for the awesome-selfhosted list if it's just a library.

2023-01-27 21:24 UTC, closed without merging