Add smartdns and smartdns-rs
awesome-selfhosted/awesome-selfhosted pull request #3509
Opened 2023-01-13 14:17 UTC by mokeyish

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding has working installation instructions.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-01-13 15:19 UTC, kokomo123 requested changes
Per the pull request template, only one item. Please separate SmartDNS-rs in a separate PR while putting SmartDNS in this PR. Thanks!

2023-01-15 03:32 UTC, mokeyish commented
I have separate SmartDNS-rs to #3512 , please review again.

2023-01-15 14:47 UTC, nodiscc requested changes

2023-01-15 14:47 UTC, nodiscc commented on README.md
> +- [SmartDNS](https://github.com/pymumu/smartdns) A local DNS server to obtain the fastest website IP for the best Internet experience, support DoT, DoH.([Source Code](https://github.com/pymumu/smartd
```suggestion
- [SmartDNS](https://github.com/pymumu/smartdns) - A local DNS server to obtain the fastest website IP for the best Internet experience, support DoT, DoH. ([Source Code](https://github.com/pymumu/smartdns)) `GPL-3.0` `C`
```

2023-01-15 14:48 UTC, nodiscc requested changes

2023-01-15 14:48 UTC, nodiscc commented on README.md
> +- [SmartDNS](https://github.com/pymumu/smartdns) A local DNS server to obtain the fastest website IP for the best Internet experience, support DoT, DoH.([Source Code](https://github.com/pymumu/smartd
```suggestion
- [SmartDNS](https://github.com/pymumu/smartdns) - A local DNS server to obtain the fastest website IP for the best Internet experience, supports DoT, DoH. `GPL-3.0` `C`
```

2023-01-15 21:18 UTC, kokomo123 approved these changes
All good to merge now, thank you.

2023-01-17 13:44 UTC, nodiscc approved these changes

2023-01-23 17:31 UTC, merged