OCS was discontinued (add an advice or remove)
awesome-selfhosted/awesome-selfhosted pull request #3533
Opened 2023-01-20 09:41 UTC by marcbria

OCS was discontinued a year ago and PKP don't recommend it any more.
It should be marked as discontinued or removed from the list.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [awesome-analytics](https://github.com/onurakpolat/awesome-analytics), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding has working installation instructions.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-01-20 20:22 UTC, nodiscc requested changes

2023-01-20 20:22 UTC, nodiscc commented on README.md
> +- [Open Conference Systems (OCS)](https://pkp.sfu.ca/ocs/) - (discontinued) Free Web publishing tool that will create a complete Web presence for your scholarly conference. ([Source Code](https://git
Thanks. This is part of https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2266

We don't keep unmaintained projects on the list and [CONTRIBUTING.md](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md) clearly says so:

> Software with no development activity for 6-12 months may be removed from the list.

Can you please remove OCS completely?

2023-01-24 22:54 UTC, nodiscc requested changes

2023-01-24 22:54 UTC, nodiscc commented on README.md
> +- [Open Conference Systems (OCS)](https://pkp.sfu.ca/ocs/) - (discontinued) Free Web publishing tool that will create a complete Web presence for your scholarly conference. ([Source Code](https://git
```suggestion
```

2023-01-24 22:55 UTC, nodiscc approved these changes

2023-01-24 22:56 UTC, merged

2023-01-25 10:56 UTC, marcbria commented
Sorry for the radio silence. I was kind of overwelmed.
Thanks for taking care of it.