Added Mathesar to "automation" list.
awesome-selfhosted/awesome-selfhosted pull request #3630
Opened 2023-03-03 19:55 UTC by kgodey

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding has working installation instructions.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-03-05 15:03 UTC, nodiscc requested changes

2023-03-05 15:03 UTC, nodiscc commented on README.md
> +- [Mathesar](https://mathesar.org/) - An intuitive UI for managing data collaboratively, for users of all technical skill levels. Built on Postgres – connect an existing DB or set up a new one. ([Dem
```suggestion
- [Mathesar](https://mathesar.org/) - An intuitive UI for managing data collaboratively, for users of all technical skill levels. Built on Postgres – connect an existing DB or set up a new one. ([Demo](https://demo.mathesar.org/), [Source Code](https://github.com/centerofci/mathesar)) `GPL-3.0` `Docker`
```
Regarding the language/platform tag:

> The Language tag is the main server-side requirement for the software
>> https://docs.mathesar.org/#installation: Currently, we only support installing using Docker Compose

Regarding the license name/syntax: we don't make a distinction between `GPL-3.0-only` and `GPL-3.0-or-later` anymore (it used to be this way but was hard to maintain and generally inaccurate, so `GPL-3.0` is now the correct label)

2023-03-05 17:06 UTC, kgodey commented
Thanks! I've accepted your proposed commit.

We will have installation instructions without Docker soon. Once we do, I assume I should make a PR to update the language/platform to `Python/Docker`. Is that correct?

2023-03-11 16:03 UTC, nodiscc approved these changes
> We will have installation instructions without Docker soon. Once we do, I assume I should make a PR to update the language/platform to Python/Docker. Is that correct?

Yes, correct

2023-03-24 15:27 UTC, nodiscc commented
I'd like to wait for https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3670 to be merged (it adds a new section `Database Management` which I think would be the most suitable for Mathesar). I'll take care of the necessary changes.

2023-03-27 16:03 UTC, kgodey commented
Thanks! I agree that makes more sense than "Automation".

2023-03-28 15:28 UTC, merged