Add Mere Medical to Miscellaneous section
awesome-selfhosted/awesome-selfhosted pull request #3731
Opened 2023-04-15 21:52 UTC by cfu288

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding has working installation instructions.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-06-05 11:29 UTC, Rabenherz112 reviewed
Is it possible to manually input data into Mere Medical, or does it solely rely on data aggregated from other services? I ask because if I need to use it alongside another service, it might be necessary to include the flag (`⚠`) since it relies on other proprietary services.

2023-06-07 06:05 UTC, cfu288 commented
Ah, it currently relies on downloading data from proprietary services because pretty much all hospital electronic medical record systems are proprietary. Once it does an initial sync of data though, the data is stored locally and Mere doesn't reach out to those proprietary services unless you need to fetch some more recent records from the hospital.

Mere doesn't support local uploads yet, but it's on the roadmap.

2023-06-07 08:26 UTC, Rabenherz112 requested changes
Thank you very much for the explanation. Considering Mere Medical's current reliance on proprietary services for the functioning of its hospital and doctor EMR systems, it is necessary to include a warning flag. This flag will inform users that the software utilizes external services beyond their control, which does not necessarily imply anything negative.

2023-06-07 08:26 UTC, Rabenherz112 commented on README.md
> +- [Mere Medical](https://meremedical.co/) - With Mere Medical, you can finally manage all of your medical records from Epic MyChart, Cerner, and OnPatient patient portals in one place. Privacy-focuse
```suggestion
- [Mere Medical](https://meremedical.co/) `⚠` - With Mere Medical, you can finally manage all of your medical records from Epic MyChart, Cerner, and OnPatient patient portals in one place. Privacy-focused, self-hosted, and offline-first. ([Demo](https://demo.meremedical.co), [Source Code](https://github.com/cfu288/mere-medical)) `GPL-3.0` `Docker/Nodejs`
```

2023-06-15 16:19 UTC, Rabenherz112 approved these changes

2023-06-19 22:57 UTC, nodiscc approved these changes

2023-06-26 12:17 UTC, merged