Add Mixpost to Analytics
awesome-selfhosted/awesome-selfhosted pull request #3862
Opened 2023-05-31 18:08 UTC by lao9s

Add Mixpost.app

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding has working installation instructions.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-06-12 13:05 UTC, lao9s commented
Hi @nodiscc 
Are there problems with this PR not being reviewed?

2023-06-29 12:42 UTC, KieranRobson requested changes
Quick change to be made

2023-06-29 12:42 UTC, KieranRobson commented on README.md
> +- [Mixpost](https://mixpost.app/) - Self-hosted social media management software. An excellent alternative to Hootsuite, Buffer, and other social media tools ([Source Code](https://github.com/inovect
```suggestion
- [Mixpost](https://mixpost.app/) - Self-hosted social media management software. An excellent alternative to Hootsuite, Buffer, and other social media tools ([Source Code](https://github.com/inovector/MixpostApp)) `MIT` `PHP/Docker`
```

> https://github.com/inovector/MixpostApp#requirements
> https://github.com/inovector/MixpostApp#docker-installation

2023-07-04 13:37 UTC, nodiscc requested changes

2023-07-04 13:37 UTC, nodiscc commented on README.md
> +- [Mixpost](https://mixpost.app/) - Self-hosted social media management software. An excellent alternative to Hootsuite, Buffer, and other social media tools ([Source Code](https://github.com/inovect
```suggestion
- [Mixpost](https://mixpost.app/) - Self-hosted social media management software. Easily create, schedule, publish, and manage social media content in one place. Alternative to Hootsuite, Buffer, and other social media tools. ([Source Code](https://github.com/inovector/MixpostApp)) `MIT` `PHP/Docker`
```

2023-07-04 14:22 UTC, nodiscc approved these changes

2023-07-10 11:39 UTC, merged