Add podcats to media streaming
awesome-selfhosted/awesome-selfhosted pull request #3889
Opened 2023-06-11 13:51 UTC by c4mbr0nn3

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding has working installation instructions.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-06-12 19:47 UTC, Rahul20001 commented
@maddox

2023-06-12 19:55 UTC, maddox commented
Unclear about the mention here.

2023-06-29 11:15 UTC, KieranRobson requested changes
Small change to be made

2023-06-29 11:15 UTC, KieranRobson commented on README.md
> +- [Podcats](https://github.com/c4mbr0nn3/podcats) - A podcast aggregator with cats. Inspired by podgrab. `GPL-3.0` `Go`
- Please change `Go` to `Docker`
> To deploy this project you need [Docker](https://www.docker.com/) installed on your server.

2023-06-29 19:56 UTC, c4mbr0nn3 commented on README.md
> +- [Podcats](https://github.com/c4mbr0nn3/podcats) - A podcast aggregator with cats. Inspired by podgrab. `GPL-3.0` `Go`
Thanks, done.

2023-07-17 12:26 UTC, nodiscc commented
Sorry, this guideline was added in the mean time (https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3999):

>  Any software project you are adding was first released more than 4 months ago.

Please resubmit when v1.0.0 is at least 4 months old.

2023-07-17 12:26 UTC, closed without merging