Add tunnelmole to Proxy
awesome-selfhosted/awesome-selfhosted pull request #3893
Opened 2023-06-12 21:14 UTC by WisdomSky

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding has working installation instructions.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-06-29 12:10 UTC, KieranRobson requested changes
A recommended description change.

2023-06-29 12:10 UTC, KieranRobson commented on README.md
> +- [Tunnel Mole](https://tunnelmole.com/) - Tunnelmole is a simple tool to give your locally running web applications a public URL. Opensource alternative to ngrok. ([Source Code](https://github.com/r
```suggestion
- [Tunnel Mole](https://tunnelmole.com/) - A simple tool to give your locally running web applications a public URL. Open source alternative to ngrok. ([Source Code](https://github.com/robbie-cahill/tunnelmole-service)) `AGPL-3.0` `Nodejs`
```

More concise description

2023-07-11 17:31 UTC, kokomo123 requested changes
Please remove the extra space and add your entry next to tinyproxy, and i think that should be good to go.

2023-07-12 14:18 UTC, WisdomSky commented
> Please remove the extra space 

May I know which extra spaces you were referring to? 

> and add your entry next to tinyproxy

It's currently next to tinyproxy.

2023-07-12 14:30 UTC, nodiscc commented
Please re-add the deleted blank line below your new entry

2023-07-12 14:52 UTC, kokomo123 commented
What nodiscc has said, apologies. I thought it was the blank space next to tinyproxy, but its a blank line below.

2023-07-12 15:34 UTC, WisdomSky commented
@nodiscc @kokomo123 

Done. Please check.

2023-07-12 17:13 UTC, nodiscc commented
Sorry, this contribution guideline was added in the mean time:

> https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/.github/PULL_REQUEST_TEMPLATE.md
>  Any software project you are adding was first released more than 4 months ago.

So this does not qualify. Please resubmit 4 months after the first stable release (there are no releases yet).

2023-07-12 17:13 UTC, closed without merging