Add yt-dlp Web UI to Automation
awesome-selfhosted/awesome-selfhosted pull request #3978
Opened 2023-07-07 11:29 UTC by arbdevml

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding has working installation instructions.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-07-08 01:22 UTC, Teresayluis approved these changes

2023-07-09 15:06 UTC, kokomo123 requested changes
I suggest you put it after YoutubeDL-Server, as i believe that should be alphabetically. Otherwise, it looks correct to me. Thanks for your contribution!

2023-07-10 10:13 UTC, arbdevml commented
> I suggest you put it after YoutubeDL-Server, as i believe that should be alphabetically. Otherwise, it looks correct to me. Thanks for your contribution!

Updated, thank you for your review.

2023-07-10 10:23 UTC, KieranRobson requested changes
Quick mistake to be corrected

2023-07-10 10:23 UTC, KieranRobson commented on README.md
> -
Could you replace this removal

2023-07-10 10:41 UTC, arbdevml commented on README.md
> -
thank you for your review.

2023-07-10 10:42 UTC, kokomo123 approved these changes
As soon as the removal is fixed, i think this is all good to go. Thanks for updating and fixing this contribution.

2023-07-10 11:12 UTC, arbdevml commented
I apologize for this question, I can not find in GitHub Web UI this option. Could you offer some advice on how to use GitHub Web UI to remove "this removal", please, or create a new pull request?

2023-07-10 12:15 UTC, kokomo123 commented
it's just a blank line so you may need to delete a space or add a space in the Web UI. Otherwise, i can try to create a new PR that fixes it.

2023-07-10 12:43 UTC, kokomo123 approved these changes
This has been successfully fixed and ready for merging. thanks!

2023-07-10 12:51 UTC, kokomo123 approved these changes

2023-07-10 18:46 UTC, nodiscc requested changes

2023-07-10 18:46 UTC, nodiscc commented on README.md
> +- [yt-dlp Web UI](https://github.com/marcopeocchi/yt-dlp-web-ui) - Web GUI for yt-dlp. `MPL-2.0` `TypeScript/Go/Docker`
```suggestion
- [yt-dlp Web UI](https://github.com/marcopeocchi/yt-dlp-web-ui) - Web GUI for yt-dlp. `MPL-2.0` `Docker/Go/Nodejs`
```

> The Language tag is the main server-side requirement for the software. Don't include frameworks or specific dialects.

Give the ordering of installation options in the project's README, this makes more sense.

2023-07-10 22:57 UTC, arbdevml commented
Thank all of you for your review, is there any issues with it, or should I change something?

2023-07-11 11:02 UTC, nodiscc approved these changes

2023-07-11 11:56 UTC, kokomo123 approved these changes
This fully works out, thanks for fixing all the fixes we have proposed and glad to have this addition to the list!

2023-07-24 20:39 UTC, merged