YetiForce added
awesome-selfhosted/awesome-selfhosted pull request #4032
Opened 2023-07-18 12:11 UTC by panchtatvam

Adding YetiForce ERP to `non-free` as per [comment on last pull request](https://github.com/awesome-selfhosted/awesome-selfhosted/pull/4031?notification_referrer_id=NT_kwDOABgfqrI3MDk1NTAyMjI0OjE1ODA5NzA#discussion_r1266558420).

- Created new category `Resource Planning - Enterprise Resource Planning` with index entry just like in `free` list
- Added YetiForce to list
- Added `YetiForce` license at bottom licenses list

----------------------------

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation
  such as title case, all caps, small caps or all lowercase.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that depend on proprietary services outside the user's control must be marked `⚠`.
  ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [x] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [x] Additions are inserted preserving alphabetical order.
- [x] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [x] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Miscellaneous`.
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another project, please provide/link to a clear list of differences between both.
- [x] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-07-18 14:53 UTC, KieranRobson requested changes
Couple of changes to be made

2023-07-18 14:53 UTC, KieranRobson commented on non-free.md
> +- [YetiForce](https://yetiforce.com/en/) - Opensource CRM ERP with sales, marketing, accounting, HR, Support, Logistics and GDPR support. ([Demo](https://gitstable.yetiforce.com/), [Source Code](http
Rather than adding `YetiForce Public License 5.0`, Please change it to `⊘ Proprietary`

2023-07-18 14:53 UTC, KieranRobson commented on non-free.md
> +- `YetiForce Public License` - [YetiForce Public License 5.0](https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/LICENSE)
Please remove this line due to the comment above.

2023-07-28 04:35 UTC, panchtatvam commented
@KieranRobson license updated as required. Please review and advise.

2023-07-28 11:15 UTC, KieranRobson approved these changes
Looks good to me now! Thanks for making the changes.

2023-08-15 13:55 UTC, nodiscc approved these changes

2023-08-22 13:01 UTC, merged