Adjust Demo link for SearX
awesome-selfhosted/awesome-selfhosted pull request #4036
Opened 2023-07-19 20:25 UTC by kokomo123

I'm adjusting the demo link as searx.space is removing all SearX instances per https://github.com/searxng/searx-instances/discussions/336

2023-07-19 20:43 UTC, Rabenherz112 commented
That doesn't really fall anymore under an interactive demo, or?
I guess it would be better to remove the link completely.

I mean, yes, if you know where to search, you can find the instances (https://github.com/searx/searx-instances/blob/master/searxinstances/instances.yml), but I wouldn't consider that interactive.

2023-07-19 20:44 UTC, kokomo123 commented
Fair enough, ill close and remove SearX in a separate PR.

2023-07-19 21:01 UTC, kokomo123 commented
> That doesn't really fall anymore under an interactive demo, or? I guess it would be better to remove the link completely.
> 
> I mean, yes, if you know where to search, you can find the instances (https://github.com/searx/searx-instances/blob/master/searxinstances/instances.yml), but I wouldn't consider that interactive.

Right, thank you for your insight. Today's one of those days for me when trying to figure it out and I overlooked your comment, and made a bunch of PRs by mistake.

2023-07-21 16:22 UTC, nodiscc commented
> That doesn't really fall anymore under an interactive demo, or?

For projects that don't have a single/official public/demo instance, but do maintain a list of public instances (which effectively are interactive demos), it's been accepted for a while that the Demo link could point to the list of public instances (otherwise we would have to arbitrarily pick one, which may have specific settings/themes, etc.).

2023-07-21 16:22 UTC, nodiscc requested changes

2023-07-21 16:22 UTC, nodiscc commented on README.md
> +- [Searx](https://searx.github.io/searx/) `⚠` - Privacy-respecting, hackable metasearch engine. [Source Code](https://github.com/searx/searx)) `AGPL-3.0` `Python`
```suggestion
- [Searx](https://searx.github.io/searx/) `⚠` - Privacy-respecting, hackable metasearch engine. ([Source Code](https://github.com/searx/searx)) `AGPL-3.0` `Python`
```

2023-07-21 17:54 UTC, kokomo123 commented
Perhaps later if its warranted, we can add back the repository for SearX that has the instances in them.

2023-07-21 18:25 UTC, nodiscc approved these changes

2023-07-24 20:41 UTC, merged