Add Zrok to Proxy section
awesome-selfhosted/awesome-selfhosted pull request #4093
Opened 2023-08-11 17:14 UTC by Nezteb

- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional. Do not add a duplicate `Source code` link if it is the same as the main link. Keep the short description under 250 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case) for it, even if the project's webpage or readme uses another capitalisation such as title case, all caps, small caps or all lowercase. `Demo` links should only be used for interactive demos, i.e. not video demonstrations. ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that depend on proprietary services outside the user's control must be marked `⚠`. ``- [Name](http://homepage/) `⚠` - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions that are not [Free software](https://en.wikipedia.org/wiki/Free_software) must be added to `non-free.md` and have the license set to `⊘ Proprietary`
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] Any license you add is in our [list of licenses](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
  If not, your addition may be inserted into `Miscellaneous`.
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [X] If you are adding software forked from another project, please provide/link to a clear list of differences between both.
- [X] The pull request title is informative, unlike "Update README.md". Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb, "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

2023-08-14 09:38 UTC, KieranRobson approved these changes
Looks good to me!

2023-08-15 17:47 UTC, nodiscc requested changes
The description should explain what the software does.

2023-08-21 11:02 UTC, nodiscc approved these changes
Much better :+1:

2023-08-21 11:03 UTC, nodiscc requested changes

2023-08-21 11:03 UTC, nodiscc commented on README.md
> +- [zrok](https://zrok.io/) - Open source serveo/ngrok alternative. Creates network tunnels that allow sharing locally running services and other private resources with others over the public Internet
Minor change to be more consistent with other entries:

```suggestion
- [zrok](https://zrok.io/) - Open source . Creates network tunnels that allow sharing locally running services and other private resources with others over the public Internet using OpenZiti (alternative to serveo/ngrok). ([Source Code](https://github.com/openziti/zrok)) `Apache-2.0` `Go`
```

2023-08-22 13:59 UTC, nodiscc commented
Hi,
thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Contributions should now be made through https://github.com/awesome-selfhosted/awesome-selfhosted-data. If you are still interested in having this software added to the list, please check contribution guidelines there, and open a new PR/issue.

Sorry for the inconvenience.

2023-08-22 13:59 UTC, closed without merging

2023-08-22 14:49 UTC, Nezteb commented
> Hi, thank you for your contribution. Today an improved version of awesome-selfhosted goes live at https://awesome-selfhosted.net/. Please check the [release announcement](https://github.com/awesome-selfhosted/awesome-selfhosted/releases/tag/1.0.0) for more details.

Neat!

I hope you don't mind that [I posted about this on the /r/selfhosted subreddit](https://www.reddit.com/r/selfhosted/comments/15y7y36/the_awesomeselfhosted_repo_released_a_new_website/). 😄